"""empty message

Revision ID: 0976bd5c649b
Revises: 5669bba2c9a4
Create Date: 2016-09-06 20:59:29.843750

"""

# revision identifiers, used by Alembic.
revision = '0976bd5c649b'
down_revision = '5669bba2c9a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time', sa.Column('day', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time', 'day')
    ### end Alembic commands ###
