"""empty message

Revision ID: 0fcbe49c47c9
Revises: 384a76d3e8c3
Create Date: 2016-09-22 12:32:32.918363

"""

# revision identifiers, used by Alembic.
revision = '0fcbe49c47c9'
down_revision = '384a76d3e8c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_name', sa.String(), nullable=True))
    op.drop_constraint('account_email_key', 'account', type_='unique')
    op.create_unique_constraint(None, 'account', ['user_name'])
    op.drop_column('account', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'account', type_='unique')
    op.create_unique_constraint('account_email_key', 'account', ['email'])
    op.drop_column('account', 'user_name')
    ### end Alembic commands ###
