"""empty message

Revision ID: 258e46968404
Revises: None
Create Date: 2016-09-23 09:18:52.689480

"""

# revision identifiers, used by Alembic.
revision = '258e46968404'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('won', sa.BOOLEAN(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu_coords', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('acc_coords', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coord')
    op.drop_table('game')
    op.drop_table('account')
    ### end Alembic commands ###
