"""empty message

Revision ID: 384a76d3e8c3
Revises: a3f70586f5f9
Create Date: 2016-09-21 12:33:59.691519

"""

# revision identifiers, used by Alembic.
revision = '384a76d3e8c3'
down_revision = 'a3f70586f5f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coord', sa.Column('board_id', sa.Integer(), nullable=True))
    op.drop_constraint('coord_board_fkey', 'coord', type_='foreignkey')
    op.create_foreign_key(None, 'coord', 'board', ['board_id'], ['id'])
    op.drop_column('coord', 'board')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coord', sa.Column('board', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'coord', type_='foreignkey')
    op.create_foreign_key('coord_board_fkey', 'coord', 'board', ['board'], ['id'])
    op.drop_column('coord', 'board_id')
    ### end Alembic commands ###
