"""empty message

Revision ID: 5178eab52e03
Revises: None
Create Date: 2016-09-20 22:50:11.203295

"""

# revision identifiers, used by Alembic.
revision = '5178eab52e03'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('won', sa.BOOLEAN(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu_positions', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('acc_positions', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('board', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('board')
    op.drop_table('game')
    op.drop_table('account')
    ### end Alembic commands ###
