"""empty message

Revision ID: 5669bba2c9a4
Revises: None
Create Date: 2016-09-05 20:07:27.132630

"""

# revision identifiers, used by Alembic.
revision = '5669bba2c9a4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('host_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('host_id'),
    sa.UniqueConstraint('host_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('time',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('seconds', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('time_id')
    )
    op.create_table('time_hosts',
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['host.host_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['time.time_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_hosts')
    op.drop_table('time')
    op.drop_table('user')
    op.drop_table('host')
    ### end Alembic commands ###
