"""empty message

Revision ID: 60960e83a48c
Revises: 258e46968404
Create Date: 2016-09-24 14:54:33.502126

"""

# revision identifiers, used by Alembic.
revision = '60960e83a48c'
down_revision = '258e46968404'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coord_game_id_fkey', 'coord', type_='foreignkey')
    op.create_foreign_key(None, 'coord', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('game_account_id_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_account_id_fkey', 'game', 'account', ['account_id'], ['id'])
    op.drop_constraint(None, 'coord', type_='foreignkey')
    op.create_foreign_key('coord_game_id_fkey', 'coord', 'game', ['game_id'], ['id'])
    ### end Alembic commands ###
