"""empty message

Revision ID: 60fb94045fbc
Revises: None
Create Date: 2016-08-24 16:08:38.150567

"""

# revision identifiers, used by Alembic.
revision = '60fb94045fbc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('time_spent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.BigInteger(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_spent')
    op.drop_table('user')
    ### end Alembic commands ###
