"""empty message

Revision ID: 7c153d3cc852
Revises: None
Create Date: 2016-09-05 17:26:30.257524

"""

# revision identifiers, used by Alembic.
revision = '7c153d3cc852'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('time_spent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seconds', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_name', sa.String(), nullable=True),
    sa.Column('time_spent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['time_spent_id'], ['time_spent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_name')
    op.drop_table('time_spent')
    op.drop_table('user_token')
    ### end Alembic commands ###
