"""empty message

Revision ID: a3f70586f5f9
Revises: 58bade0fd6cb
Create Date: 2016-09-21 12:22:57.512447

"""

# revision identifiers, used by Alembic.
revision = 'a3f70586f5f9'
down_revision = '58bade0fd6cb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu_coords', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('acc_coords', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('board', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('position')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cpu_positions', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('acc_positions', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('board', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board'], ['board.id'], name='position_board_fkey'),
    sa.PrimaryKeyConstraint('id', name='position_pkey')
    )
    op.drop_table('coord')
    ### end Alembic commands ###
