"""empty message

Revision ID: def81afaea89
Revises: e3e9827208e6
Create Date: 2016-09-05 12:01:58.716879

"""

# revision identifiers, used by Alembic.
revision = 'def81afaea89'
down_revision = 'e3e9827208e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_spent', sa.Column('seconds', sa.BigInteger(), nullable=True))
    op.drop_column('time_spent', 'minutes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_spent', sa.Column('minutes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('time_spent', 'seconds')
    ### end Alembic commands ###
