"""empty message

Revision ID: df42960f1fd5
Revises: None
Create Date: 2016-09-20 20:50:03.099031

"""

# revision identifiers, used by Alembic.
revision = 'df42960f1fd5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    ### end Alembic commands ###
