"""empty message

Revision ID: e3e9827208e6
Revises: None
Create Date: 2016-08-28 20:28:45.114837

"""

# revision identifiers, used by Alembic.
revision = 'e3e9827208e6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('time_spent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('time_spent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['time_spent_id'], ['time_spent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_name')
    op.drop_table('time_spent')
    op.drop_table('user_token')
    ### end Alembic commands ###
